### ISSUE TITLE
Performance disparity between raw HTTP REST queries and built-in HTTP client

### ISSUE THREAD

**Issue by theronic** [xtdb/xtdb#891] opened 2020-05-25 11:22 UTC
When querying an empty Crux node spun up on a DigitalOcean box from the [crux-standalone Docker image](https://hub.docker.com/r/juxt/crux-standalone) (in-memory KV store, no txes yet), the empty result set comes back ~2x as fast via the HTTP REST API when compared to the built-in HTTP client API for the same query.

Compare running this query (which should return the empty set as a result):

```
(ns crux-test
  (:require [dotenv :refer (env app-env)]
            [taoensso.timbre :as log]
            [org.httpkit.client :as http]))

(def crux-node-url (env "CRUX_NODE_URL"))

(defn q [query]
  (http/post
    (str crux-node-url "/query")
    {:headers {"Content-Type" "application/edn"}
     :body    (pr-str {:query query})}))

(time (read-string (slurp (:body @(q '{:find  [?last-name]
                                         :where [[?person :first-name "John"]
                                                 [?person :last-name ?last-name]]})))))
"Elapsed time: 353.379041 msecs"
=> #{}
```
If I run it several times, the elapsed time converges to ~170ms.

## Compared to the built-in HTTP client:

```
(def crux-client (crux/new-api-client crux-node-url)

(let [db (crux/db crux-client)] ;; not profiling call to crux/db
    (time (crux/q db '{:find  [?last-name]
                       :where [[?person :first-name "John"]
                               [?person :last-name ?last-name]]})))
"Elapsed time: 329.54181 msecs"
=> #{}
```

This query time stays at around ~330ms no matter how many times I repeat it, which still feels suuuper slow to me for a query against an empty DB.

Could this be HTTP pipelining that's resulting in the time difference?

When I run the query directly on the DigitalOcean box, the query returns in about 18ms.

**Comment by theronic** [comment] 2020-05-25 13:15
Return-trip ping to the box is ~163ms:
```
12 packets transmitted, 12 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 163.622/170.051/218.483/14.715 ms
```

**Comment by refset** [comment] 2020-05-25 13:35
Hi @theronic it looks to me like there must be an extra http roundtrip happening. Before we dig in further though, can you try forcing the client to definitely use httpkit (as opposed to clj-http) and see what happens?

See the comments on rebinding the var to configure: https://github.com/juxt/crux/blob/master/crux-http-client/src/crux/remote_api_client.clj#L29

**Comment by theronic** [comment] 2020-05-25 15:01
What should the with-bindings call look like? I'm getting errors for this:

```
(require '[org.httpkit.client :as http])
(with-bindings [crux.remote-api-client/*internal-http-request-fn* http/request]
    (let [db (crux/db crux-client)]
      (time (crux/q db '{:find  [?order ?total]
                         :where [[?order :sales-order/total ?total]]}))))
=> Execution error (ClassCastException) at bridge.data.crux-server/eval12041 (crux_server.clj:72).
crux.remote_api_client$init_internal_http_request_fn$fn__9039$fn__9040$fn__9041 cannot be cast to clojure.lang.IMapEntry
```

Also tried `(with-bindings [crux.remote-api-client/*internal-http-request-fn* http/post] ...)` - same result.

**Comment by theronic** [comment] 2020-05-25 17:27
Whoops, with-bindings takes a map, not a vector of pairs. So I tried this:

```
(with-bindings {#'crux.remote-api-client/*internal-http-request-fn* org.httpkit.client/request}
    (let [client (start-http-client)
          db     (crux/db client)]
      (time (crux/q db '{:find  [?order ?total]
                         :where [[?order :sales-order/total ?total]]}))))
=> Execution error (NullPointerException) at crux.remote-api-client/api-request-sync (remote_api_client.clj:87).
null
```

I reviewed [the code in `src/crux/remote_api_client.clj`](https://github.com/juxt/crux/blob/master/crux-http-client/src/crux/remote_api_client.clj#L73), but I don't see anything that would trigger two roundtrips.

**Comment by theronic** [comment] 2020-05-26 07:33
Could it perhaps be a redirect, or an SSL negotiation? What steps would I take to trace execution in Clojure to see what's going on under the bonnet?

**Comment by refset** [comment] 2020-05-29 15:02
Thanks for ruling out the binding config as a possible reason.

I've done some sanity checking to confirm everything is happening as we would expect when running various combinations of nodes & clients in a local repl and also when using the container version locally (`juxt/crux-standalone:20.05-1.8.4-alpha`). Nothing jumps out that suggests any reasons why you might be seeing different HTTP behaviours depending on how you generate the HTTP requests (remote client vs. normal Clojure http call).

Are you able to reproduce this problem with a local container setup?

Can you describe more about how Digital Ocean is adding SSL? SSL definitely involves extra round-trips. Is there a load balancer?

Another option is to inspect your network traffic for clues using a proxy, perhaps something like this: https://www.charlesproxy.com/ (I have no idea if this is a good tool or not, but it looks like it could be helpful for you)

**Comment by refset** [comment] 2020-06-09 10:17
I will close this for the time being but let's reopen it again as soon as anyone manages to consistently reproduce the issue. Please feel free to continue the conversation on Zulip/Slack for any further help with debugging your specific setup, or alternatively, respond here if you discover any new clues about what's been happening :)

I hope it's not too big a blocker for your development work. I can certainly see that it would be useful to have a polished "Get Crux running on Digital Ocean" tutorial to save you from this kind of headache in future!

**Closed as completed by refset** 2020-06-09 10:17 UTC
Labels: 1.x
