### ISSUE TITLE
Intermittent test - `api-test/test-tx-log`

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#1255] opened 2020-11-13 10:50 UTC
See https://app.circleci.com/pipelines/github/juxt/crux/1597/workflows/74cd46e9-9742-4378-a028-b7c7bd09edfe/jobs/6405

```
FAIL in (test-tx-log) (api_test.clj:275)
:local-kafka tx-log tx fns return with-ops? correctly
expected: (= [:crux.tx/fn (c/new-id :increment-age-2) #:crux.api{:tx-ops [[:crux.tx/fn (c/new-id :increment-age) #:crux.api{:tx-ops [[:crux.tx/put {:crux.db/id :jack, :age 22}]]}]]}] (last tx-ops))
  actual: (not (= [:crux.tx/fn #crux/id "7b3961b3ed263aff1adde3e92a29eeb550380d1e" #:crux.api{:tx-ops [[:crux.tx/fn #crux/id "46995cbc65f1a439b86a848bb3506bce65e8f6ca" #:crux.api{:tx-ops [[:crux.tx/put {:crux.db/id :jack, :age 22}]]}]]}] [:crux.tx/fn #crux/id "7b3961b3ed263aff1adde3e92a29eeb550380d1e" {:crux.db.fn/args (:jack), :crux.api/tx-ops ()}]))
```

**Comment by jarohen** [comment] 2020-11-27 13:59
duplicate of #1256

**Closed as completed by jarohen** 2020-11-27 13:59 UTC
Labels: 1.x
