### ISSUE TITLE
WARN  crux.tx: Falling behind :crux.tx/event-log

### ISSUE THREAD

**Issue by tonsky** [xtdb/xtdb#210] opened 2019-05-13 10:37 UTC
Running just 10 transactions with two puts in each results in a

```
13:33:59.096 WARN  crux.tx: Falling behind :crux.tx/event-log at: 1595129486369794 end: 1595129486427138
```

in a log. How bad is it? How to avoid? I’m on standalone `crux.kv.rocksdb.RocksKv`

**Comment by hraberg** [comment] 2019-05-13 10:41
Hi @tonsky, thanks! We'll likely change this message and log level. This is normal behaviour, it just tells you that the index isn't up-to-date (yet). There will always be a slight lag by design.

**Comment by tonsky** [comment] 2019-05-13 10:58
Any way to guarantee I will see my own writes? I tried both

```
(crux.api/sync system nil)
```

and

```
(crux.api/sync system (java.time.Duration/ofSeconds 1))
```

and they both end up with

```
{:clojure.main/message
 "Execution error (NullPointerException) at crux.tx/await-no-consumer-lag$fn (tx.clj:397).\nnull\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.NullPointerException,
  :clojure.error/line 397,
  :clojure.error/symbol crux.tx/await-no-consumer-lag$fn,
  :clojure.error/source "tx.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.lang.NullPointerException,
    :at [clojure.lang.RT longCast "RT.java" 1284]}],
  :trace
  [[clojure.lang.RT longCast "RT.java" 1284]
   [crux.tx$await_no_consumer_lag$fn__19936 invoke "tx.clj" 397]
   [crux.io$wait_while invokeStatic "io.clj" 117]
   [crux.io$wait_while invoke "io.clj" 114]
   [crux.tx$await_no_consumer_lag invokeStatic "tx.clj" 397]
   [crux.tx$await_no_consumer_lag invoke "tx.clj" 390]
   [crux.bootstrap.CruxNode sync "bootstrap.clj" 106]
   [crux.bootstrap.standalone.StandaloneSystem
    sync
    "standalone.clj"
    60]
   [crux.api$eval1147$fn__1160 invoke "api.clj" 129]
   [crux.api$eval972$fn__1015$G__955__1022 invoke "api.clj" 9]
   [grumpy.migrations.to_4$migrate_BANG_ invokeStatic "to_4.clj" 65]
   [grumpy.migrations.to_4$migrate_BANG_ invoke "to_4.clj" 54]
   [grumpy.migrations$maybe_migrate_to
    invokeStatic
    "migrations.clj"
    16]
   [grumpy.migrations$maybe_migrate_to invoke "migrations.clj" 13]
   [grumpy.migrations$migrate_BANG_ invokeStatic "migrations.clj" 24]
   [grumpy.migrations$migrate_BANG_ invoke "migrations.clj" 21]
   [grumpy.migrations$_main invokeStatic "migrations.clj" 28]
   [grumpy.migrations$_main doInvoke "migrations.clj" 27]
   [clojure.lang.RestFn invoke "RestFn.java" 397]
   [clojure.lang.AFn applyToHelper "AFn.java" 152]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 665]
   [clojure.main$main doInvoke "main.clj" 618]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]]}}
```

**Comment by hraberg** [comment] 2019-05-13 11:01
This looks related to #205 which @megakorre recently fixed on master I think.

An alternative way is to provide the transaction time you get from the `submit-tx` call to your `db` call.

**Comment by megakorre** [comment] 2019-05-13 13:06
Created a PR with the change in log level to debug https://github.com/juxt/crux/pull/212.

**Comment by megakorre** [comment] 2019-05-13 13:15
Yes the above issue no longer throws a NP exception. You now get a timeout exception (after the given timeout has expired).
There is a standing issue to not have it throw any error when the database is empty to https://github.com/juxt/crux/issues/211

**Closed as completed** 2019-05-13 18:39 UTC
Labels: dev-experience, 1.x
