### ISSUE TITLE
crux.api/with-tx cannot be applied recursively

### ISSUE THREAD

**Issue by malcolmsparks** [xtdb/xtdb#1492] opened 2021-04-05 10:39 UTC
This passes: 

```clojure
(-> (db)
    (x/with-tx [[:crux.tx/put {:crux.db/id :a}]]))
#<CruxDB {:crux.db/valid-time #inst "2021-04-05T10:34:28.320-00:00", :crux.tx/tx-id 5168}>
```

But this fails:
```clojure
(-> (db) 
    (x/with-tx [[:crux.tx/put {:crux.db/id :a}]]) 
    (x/with-tx [[:crux.tx/put {:crux.db/id :b}]]))
```
with:
```
Execution error (IllegalArgumentException) at crux.db/eval19266$fn$G (db.clj:26).
No implementation of method: :latest-completed-tx of protocol: #'crux.db/IndexStore found for class: crux.kv.index_store.KvIndexStoreTx
```

My use-case is taking an existing 'speculative' database and wanting to apply a couple of extra entities, and it would be _really_ nice if this worked. Also, in testing, this means that using a speculative database in tests cannot be used to test any code that itself has speculative transactions.

No urgency, I can work around it.

**Comment by refset** [comment] 2021-04-05 13:03
Duplicate of https://github.com/juxt/crux/issues/1434 which is already on the backlog for the next few weeks, but thank you @malcolmsparks for the added context and motivation!

**Closed as completed by refset** 2021-04-05 13:03 UTC
Labels: 1.x
