### ISSUE TITLE
start-node on OS X with Java 16 causes Clojure to crash

### ISSUE THREAD

**Issue by jaybarra** [xtdb/xtdb#1564] opened 2021-07-03 22:14 UTC
I am seeing a bug where crux fails immediately after attempting to start a node. It will bring down the REPL when attempting start a node with a SIGABRT code.

## Environment
OSX 11.4 Big Sur
Clojure CLI version 1.10.3.855
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

## How to reproduce

Create a deps.edn containing the following

### deps.edn
```clojure
{:paths ["src"]
 :deps {juxt/crux-core {:mvn/version "21.06-1.17.1-beta"}
        juxt/crux-rocksdb {:mvn/version "21.06-1.17.1-beta"}
        org.clojure/clojure {:mvn/version "1.10.3"}}}
```

### src/core.clj
```clojure
(ns core
  (:require
   [crux.api :as crux]))

(def crux-node
  (crux/start-node {}))
```

Start a REPL with `clj` and enter the following

```
> clj
Clojure 1.10.3
user=> (require '[core])
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: /usr/local/Cellar/openjdk/16.0.1/libexec/openjdk.jdk/Contents/Home/bin/java is loading libcrypto in an unsafe way

rlwrap: warning: clojure crashed, killed by SIGABRT.
rlwrap itself has not crashed, but for transparency,
it will now kill itself (without dumping core) with the same signal

warnings can be silenced by the --no-warnings (-n) option
[1]    79392 abort      clj
```

**Comment by jarohen** [comment] 2021-07-05 12:33
Hey @jaybarra, thanks for getting in touch :wave: I reckon this is a duplicate of #894 - unfortunately we're still unsure as to the cause of that as yet.

James

**Closed as completed by jarohen** 2021-07-05 12:33 UTC
Labels: duplicate, 1.x
