### ISSUE TITLE
(crux/status node) crashes JRE

### ISSUE THREAD

**Issue by theronic** [xtdb/xtdb#368] opened 2019-10-26 14:23 UTC
```
(crux/status *node)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000012d2fdc27, pid=79779, tid=0x000000000000fc03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_141-b15) (build 1.8.0_141-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.141-b15 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni-osx.jnilib+0x1ac27]  Java_org_rocksdb_RocksDB_getProperty+0x57
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/petrus/Projects/acct/hs_err_pid79779.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```

**Comment by jonpither** [comment] 2019-10-28 17:12
Thanks @theronic we will take a look

**Comment by jonpither** [comment] 2019-10-30 11:29
Hi @theronic This currently happens if you attempt to call `status` against a closed node. I have raised #369 to protect against this that we will consider merging.

If you don't think this issue is due to calling `status` against a closed node, then we can reopen, and please provide more details of your Crux setup, so that we can reproduce.

**Comment by jonpither** [comment] 2019-10-30 11:29
Actually will leave this open until the PR is merged.

**Closed as completed** 2019-11-14 10:35 UTC
Labels: 1.x
