### ISSUE TITLE
Add support for `ANY(array expr)`

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#3555] opened 2024-08-05 09:57 UTC
See [Postgres](https://www.postgresql.org/docs/current/functions-comparisons.html#FUNCTIONS-COMPARISONS-ANY-SOME), to better support JS SQL tooling (Slonik).

**Comment by egg-juxt** [comment] 2024-08-05 10:47
Duplicate of https://github.com/xtdb/xtdb/issues/3539

**Closed by egg-juxt** 2024-08-05 10:47 UTC
Labels: sql, postgres-sql
