### ISSUE TITLE
Missing reader literal '#crux/id'

### ISSUE THREAD

**Issue by ThomasKaemmerer** [xtdb/xtdb#260] opened 2019-06-16 12:05 UTC
In (https://juxt.pro/crux/docs/transactions.html#_valid_ids] the usage of the #crux/id reader literal is described as "...will take any string and attempt to coerce it into a valid ID.".
I've tried it with the standalone web-application (docker image latest, digest: sha256:074b0d315f191b3c9bcd973a4ea1cd59d987c4ef7a0baf1bb8088829a804d99c) but it fails:
`{:type java.lang.RuntimeException,
   :message "No reader function for tag crux/id",
   :at
   [clojure.lang.EdnReader$TaggedReader
    readTagged
    "EdnReader.java"
    801]}`
The EDN used in the call contains `:crux.db/id #crux/id "de:db:SBRM:S:35133"`.

**Comment by refset** [comment] 2019-06-20 17:17
Hi @ThomasKaemmerer thank you for opening the issue. I agree it is a problem and we will resolve it ASAP.

I'm not familiar enough with how the `data_readers.clj` system works, but this looks like relevant reading for the team: https://groups.google.com/forum/#!topic/clojure/B4_uGy1VhnA

**Comment by spacegangster** [comment] 2019-06-24 16:22
Confirmed. Working on this in #272.

**Comment by refset** [comment] 2019-06-27 08:48
Hopefully fixed now at https://github.com/juxt/crux/commit/46d51949564b9ca12886e9d98a7121cd3f7d63f1. Thanks again for reporting this!

**Closed as completed by refset** 2019-06-27 08:48 UTC
Labels: good first issue, 1.x
