### ISSUE TITLE
Build Java 101 Tutorial and validate Java API

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#273] opened 2019-06-25 08:23 UTC
1. ~~e.g. is it okay to return results as Clojure maps?~~
2. Config map builder

**Comment by SevereOverfl0w** [comment] 2019-06-25 10:01
Don't clojure maps extend java.util.HashMap, and this is therefore okay?

**Comment by refset** [comment] 2019-06-25 13:34
I think we'll know for sure once someone has tried to build a tutorial or something non-trivial with Java. I would like to understand how Crux looks & feels in normal Java tooling (e.g. https://www.jetbrains.com/idea/download/#section=linux) and know whether there are any other possible impacts of leaving it how it is.

Maybe the simple fix is to sprinkle `(java.util.HashMap. crux-result-map)` in a few places.

**Comment by hraberg** [comment] 2019-06-26 06:45
Clojure maps should be OK, they're read only from the Java API's POV, but implement `java.util.Map`. Not saying there aren't other usability issues here with keywords etc, but the maps themselves are fine.

**Comment by hraberg** [comment] 2019-06-26 09:04
There are several ways for a Java user to create a Clojure keyword necessary to actually look something up in these maps, here's one way via the official API:
`clojure.java.api.Clojure.read(":foo")`

Another, cleaner but lower level way is:
`clojure.lang.Keyword.intern("foo")`

**Comment by hraberg** [comment] 2019-06-26 09:05
Also, there's a difference between the few maps we do have in the API itself (submitted tx, status etc.) which we could actually add Java objects for, and the results themselves, which are usually tuples (list), so no keywords are necessary to be used.

**Comment by hraberg** [comment] 2019-11-14 10:45
Closing this as basically a duplicate of #360.

**Closed as completed by hraberg** 2019-11-14 10:45 UTC
Labels: 1.x
